### ISSUE TITLE
Task #3

### ISSUE THREAD

**Issue by WolffM** [WolffM/webcomicreact#5]
* Fix favicon Missing.
* Fix assets/26.png Missing.
* Fix Anchoring of image at the bottom of the screen
* Add navigation bar component

**Comment by erinwolff** [comment]
- fix functionality of previous button (update z-index)
- fix centering of spinner

**Comment by erinwolff** [comment]
- assets/26.png missing is a non-issue. Resolved.

**Comment by erinwolff** [comment]
change favicon to chess king (transparent image)

**Comment by erinwolff** [comment]
Of the above, the remaining points are open issues: 
- change favicon to chess king (transparent image)
- Add navigation bar component
- add pop ups/toast to let users know how to navigate between images

**Comment by erinwolff** [comment]
still need to:

- add pop ups/toast to let users know how to navigate between images
- ensure horizontal rotation doesn't cut image off
- add nested menu for viewing Story>Chapter
